### ISSUE TITLE
Trying to install balancer

### ISSUE THREAD

**Issue by MaartenKool** [cthacker/class-balancer#1]
@cthacker Hi Cameron, trying to install the balancer. Am running into loads of issues with numpy/scipy versions. Is there an easy way around that?

Many thanks,

Maarten

**Comment by cthacker** [comment]
Hi, as long as you have numpy/scipy installed you can try removing the version dependance in setup.py to use older versions. Are you not able to install newer versions of numpy? The minimum requirement in this repo is fairly old already.

**Comment by MaartenKool** [comment]
Hi Cameron,

Did some work over the Christmas hols and got it working fine, also noted you update the print statements to python 3.x.
Thanks for that,

Playing around with the sample size a bit as I am getting many synthetic records created. So who knows I may suggest /fork an update

Take care,
Maarten
